name: Telegram Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: curl -s "https://api.telegram.org/bot8667226754:AAFINvhhbBmzqMy5hZgRv3SrG58coiBC6Bk/sendMessage?chat_id=999772135&text=GitHub%20Action%20Works"